"""updated check constraints on phone number

Revision ID: 22bc4c4b6444
Revises: f8fc3a0cc293
Create Date: 2024-06-19 16:54:57.836868

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '22bc4c4b6444'
down_revision = 'f8fc3a0cc293'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('volunteers', schema=None) as batch_op:
        batch_op.drop_constraint('ck_volunteers_phone_number_length_ten')
        batch_op.create_check_constraint('phone_number_length', 'length(phone_number) = 10 or length(phone_number) = 12 or length(phone_number) = 15 or length(phone_number) = 17')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('volunteers', schema=None) as batch_op:
        batch_op.drop_constraint('phone_number_length')

    # ### end Alembic commands ###
